version: '1.0'
services:

    db:
        image: mongodb
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - backend
        deploy:
            placement:
            constraints:
                - "node.role==manager"

  web:
    build: .
    ports:
        - "4000:4000"
    volumes:
        - .:/code
        - logvolume01:/var/log
    links:
        - node
    node:
        image: node:12
volumes:
  logvolume01: {}